version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errcheck
    - gosec
    - unconvert
    - misspell

linters-settings:
  staticcheck:
    checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
