version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - errcheck
    - gosec
    - unconvert
    - misspell
  settings:
    staticcheck:
      checks: ["all"]

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
